services:
  # Base de Datos Transaccional
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=subastas_db
      - MYSQL_ROOT_PASSWORD=password123
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Caché
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  # Message Broker (Comandos / Tareas Específicas)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: subastas-rabbitmq
    ports:
      - "5672:5672"   # Puerto interno para Spring Boot
      - "15672:15672" # Puerto para el panel web (UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  # ------------------------------------------------
  # BROKER DE EVENTOS: APACHE KAFKA (Streaming de Datos)
  # ------------------------------------------------
  kafka:
    image: apache/kafka:3.7.0
    container_name: broker-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # ------------------------------------------------
  # BASE DE DATOS ANALÍTICA (Para Power BI)
  # ------------------------------------------------
  postgres-analytics:
    image: postgres:15-alpine
    container_name: db-analytics
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=analytics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Microservicios
  servicio-subastas:
    build: ./servicio-subastas
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      - mysql
    restart: on-failure

  servicio-wallet:
    build: ./servicio-wallet
    ports:
      - "8081:8081"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      - mysql
    restart: on-failure

  servicio-bidding:
    build: ./servicio-bidding
    ports:
      - "8082:8082"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      - mysql
      - rabbitmq
    restart: on-failure

  servicio-usuarios:
    build: ./servicio-usuarios
    ports:
      - "8083:8083"
    environment:
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      - mysql
    restart: on-failure

  servicio-notificaciones:
    build: ./servicio-notificaciones
    container_name: servicio-notificaciones
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - rabbitmq
    restart: on-failure

  api-gateway:
    build: ./api-gateway
    ports:
      - "9000:9000"
    environment:
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      - servicio-usuarios
      - servicio-subastas
      - servicio-wallet
      - servicio-bidding
      - redis
    restart: on-failure

volumes:
  mysql_data:
  postgres_data: # Persistencia para PostgreSQL