spring.application.name=servicio-bidding
server.port=8082

# Timeout para Feign
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bidding_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate creará la tabla automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Activar OkHttp para que Feign soporte el método PATCH
spring.cloud.openfeign.okhttp.enabled=true

# Formato de log personalizado para incluir el Correlation ID
logging.pattern.level=%5p [TraceId: %X{correlationId:-NO-ID}]