spring.application.name=servicio-bidding
server.port=8082

# Esta propiedad la dejamos lista para que Feign no nos tire timeout si un servicio tarda un poquito
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000