spring.application.name=servicio-notificaciones

server.port=8084

# ==========================================
# CONFIGURACIÓN DE RABBITMQ
# ==========================================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ==========================================
# CONFIGURACIÓN DE CORREO (GMAIL SMTP - PRODUCCIÓN)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jeronimopizarro03@gmail.com
spring.mail.password=qlqu pyxh phbo fima
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Formato de logs prolijo con ID de correlación
logging.pattern.level=%5p [TraceId: %X{correlationId:-NO-ID}]

# Le decimos a Spring Boot que NO levante un servidor web embebido (Tomcat)
spring.main.web-application-type=none