spring.application.name=servicio-subastas

# mysql-db, createDatabaseIfNotExist y password123
spring.datasource.url=jdbc:mysql://mysql-db:3306/subastas_db?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password123

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

logging.pattern.level=%5p [TraceId: %X{correlationId:-NO-ID}]

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha