spring.application.name=servicio-analytics
server.port=8085

# ==========================================
# CONFIGURACIÓN DE POSTGRESQL (BASE DE DATOS PARA POWER BI)
# ==========================================
spring.datasource.url=jdbc:postgresql://db-analytics:5432/analytics_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONFIGURACIÓN DE APACHE KAFKA (CONSUMIDOR)
# ==========================================
spring.kafka.bootstrap-servers=kafka:9092

# Identificador del grupo que va a escuchar (Consumer Group)
spring.kafka.consumer.group-id=analytics-group
# earliest: Si el servicio se apaga, cuando vuelva a prender leerá los mensajes que se perdió
spring.kafka.consumer.auto-offset-reset=earliest

# Deserializadores: Convierten el JSON que viene de Kafka a un Objeto Java
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Seguridad: Le decimos a Spring Boot que confíe en cualquier paquete JSON que llegue
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Tópico a escuchar
topic.analytics.bidding=analytics-bids-topic

# Le decimos que ignore las etiquetas de clase del productor
spring.kafka.consumer.properties.spring.json.use.type.headers=false
# Le decimos a qué clase local debe forzar la conversión del JSON
spring.kafka.consumer.properties.spring.json.value.default.type=com.portafolio.analytics.infrastructure.event.BidAnalyticsEvent