spring.application.name=servicio-wallet
# PUERTO DIFERENTE: Como Subastas usa el 8080 por defecto, Wallet debe usar otro para que ambos puedan correr al mismo tiempo.
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/wallet_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
