spring.application.name=servicio-wallet
server.port=8081

# Apuntamos a wallet_db, NO a users_db
spring.datasource.url=jdbc:mysql://mysql-db:3306/wallet_db?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password123

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

logging.pattern.level=%5p [TraceId: %X{correlationId:-NO-ID}]

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha

# Configuracion JWT compartida con el Gateway
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=604800000